const eventsData = [
  {
    id: 1,
    title: "Annual Sports 2024",
    date: "2025-12-16",
    description:
      "Our yearly gathering of developers, students, and industry experts.",
    images: [
      "/events/sports/img-1.jpeg",
      "/events/sports/img-2.jpeg",
      "/events/sports/img-3.jpeg",
      "/events/sports/img-4.jpeg",
      "/events/sports/img-5.jpeg",
      "/events/sports/img-6.jpeg",
      "/events/sports/img-7.jpeg",
      "/events/sports/img-8.jpeg",
      "/events/sports/img-9.jpeg",
      "/events/sports/img-10.jpeg",
      "/events/sports/img-11.jpeg",
      "/events/sports/img-12.jpeg",
      "/events/sports/img-13.jpeg",
      "/events/sports/img-14.jpeg",
      "/events/sports/img-15.jpeg",
      "/events/sports/img-16.jpeg",
      "/events/sports/img-17.jpeg",
      "/events/sports/img-18.jpeg",
      "/events/sports/img-19.jpeg",
      "/events/sports/img-20.jpeg",
      "/events/sports/img-21.jpeg",
      "/events/sports/img-22.jpeg",
    ],
  },
  {
    id: 2,
    title: "Annual Lunch 2025",
    date: "2025-12-16",
    description:
      "Our yearly gathering of developers, students, and industry experts.",
    images: [
      "/events/sports/img-1.jpeg",
      "/events/sports/img-2.jpeg",
      "/events/sports/img-3.jpeg",
      "/events/sports/img-4.jpeg",
      "/events/sports/img-5.jpeg",
      "/events/sports/img-6.jpeg",
      "/events/sports/img-7.jpeg",
      "/events/sports/img-8.jpeg",
      "/events/sports/img-9.jpeg",
      "/events/sports/img-10.jpeg",
      "/events/sports/img-11.jpeg",
      "/events/sports/img-12.jpeg",
      "/events/sports/img-13.jpeg",
      "/events/sports/img-14.jpeg",
      "/events/sports/img-15.jpeg",
      "/events/sports/img-16.jpeg",
      "/events/sports/img-17.jpeg",
      "/events/sports/img-18.jpeg",
      "/events/sports/img-19.jpeg",
      "/events/sports/img-20.jpeg",
      "/events/sports/img-21.jpeg",
      "/events/sports/img-22.jpeg",
    ],
  },
];

export default eventsData;
