const members = [
  {
    id: 1,
    prefix: "Mr",
    firstName: "Shahazad",
    lastName: "Hussain",
    designation: "Advisor",
    image: "/members/img-1.jpg",
  },
  {
    id: 14,
    prefix: "Ms",
    firstName: "Aneeza",
    lastName: "Alam",
    designation: "Female Coordinator",
    image: "",
  },
  {
    id: 2,
    prefix: "Mr",
    firstName: "Hunain",
    lastName: "Shahid",
    designation: "President",
    image: "",
  },

  {
    id: 3,
    prefix: "Ms",
    firstName: "Alishba",
    lastName: "Qadir",
    designation: "Vice-President - Female",
    image: "",
  },
  {
    id: 4,
    prefix: "Mr",
    firstName: "Noman",
    lastName: "Amanullah",
    designation: "Vice-President - Male",
    image: "",
  },
  {
    id: 5,
    prefix: "Mr",
    firstName: "Syed Ali",
    lastName: "Ahmad",
    designation: "General Secretary",
    image: "",
  },
  {
    id: 6,
    prefix: "Ms",
    firstName: "Bisma",
    lastName: "Irshad",
    designation: "Finance Secretary - Female",
    image: "",
  },
  {
    id: 7,
    prefix: "Mr",
    firstName: "Umar",
    lastName: "Javed",
    designation: "Finance Secretary - Male",
    image: "",
  },
  {
    id: 8,
    prefix: "Mr",
    firstName: "Danish",
    lastName: "Afzal",
    designation: "Event Manager - Male",
    image: "",
  },
  {
    id: 9,
    prefix: "Ms",
    firstName: "Fatima",
    lastName: "Shoukat",
    designation: "Event Manager - Female",
    image: "",
  },
  {
    id: 10,
    prefix: "Mr",
    firstName: "Hamza",
    lastName: "Naeem",
    designation: "Media Head",
    image: "",
  },
  {
    id: 11,
    prefix: "Mr",
    firstName: "Moazzan",
    lastName: "Ali",
    designation: "Social Media Head",
    image: "",
  },
  {
    id: 12,
    prefix: "Mr",
    firstName: "Muhammad",
    lastName: "Hanzla",
    designation: "Event Manager",
    image: "",
  },
  {
    id: 13,
    prefix: "Mr",
    firstName: "Muhammad",
    lastName: "Bin Tariq",
    designation: "General Member",
    image: "",
  },
];

export default members;
